name: composer

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer validate --strict

  normalize:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer global config allow-plugins.ergebnis/composer-normalize true
      - run: composer global require ergebnis/composer-normalize:^2.52
      - run: composer normalize --dry-run
