name: move-private-assets

on:
  push:
    branches:
      - statamic-cms
    paths:
      - .github/workflows/move-private-assets.yml

permissions:
  contents: write

jobs:
  move:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7
        with:
          ref: statamic-cms
          fetch-depth: 0
      - name: Move images above webroot
        run: |
          mkdir -p resources
          git mv public/images resources/images
          printf '*\n!index.php\n!.gitignore\n' > public/.gitignore

          git add -A

          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m "Move Statamic images above webroot"
          git push origin HEAD:statamic-cms
