name: phpstan

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      APP_ENV: testing
      APP_KEY: base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
      - run: composer install --prefer-dist --no-interaction --no-scripts
      - run: php artisan package:discover --ansi --no-interaction
      - run: composer phpstan
